(*---------------------------------------------------------------------------
   Copyright (c) 2025 Orcaset. All rights reserved.
   SPDX-License-Identifier: SSPL-1.0
  ---------------------------------------------------------------------------*)

(** Financial schedule generation.

    A schedule is a finite sequence of date boundaries defining contiguous periods, typically
    representing payment or accrual dates for a financial instrument. Each boundary carries both an
    {e unadjusted} date (from the generation rule) and an {e adjusted} date (after applying a
    {!Calendar.bdc}). Unadjusted dates are used for accrual calculations; adjusted dates determine
    when cash moves.

    Schedules are generated from a date range and a {!Period.offset}, with optional conventions for
    {!roll}, {!stub} handling, and business day adjustment. Convert the result to a {!Timeline.t}
    via {!to_timeline} for use with {!Series.eval}.

    {[
      let sched =
        Schedule.make ~start_date:(Date.make 2025 2 15) ~end_date:(Date.make 2030 2 15)
          ~offset:(Period.make_offset ~quarters:1 ())
          ~bdc:Modified_following ~calendar:Calendar.weekdays ()

      let loan_tl = Schedule.to_timeline sched
      let values = Series.eval loan_tl interest
    ]}

    {b Schedule vs Timeline.} {!Timeline.make} shifts dates sequentially, which causes day-of-month
    drift for end-of-month start dates (e.g. [Jan 31 -> Feb 28 -> Mar 28]). {!make} avoids this by
    computing each date as a multiple of the offset from a fixed anchor, preserving the original
    day-of-month (e.g. [Jan 31 -> Feb 28 -> Mar 31]).

    {1 Roll conventions} *)

(** The type for roll conventions. Determines the day-of-month for generated interior dates. The
    roll is applied after month arithmetic, so it only affects the day component. *)
type roll =
  | Same_day
      (** Maintain the anchor's day-of-month, clamping when the target month has fewer days.
          {b Default.} *)
  | End_of_month  (** Land on the last day of the target month. *)
  | Day_of_month of int
      (** Land on the given day, clamping when the target month has fewer days. *)

(** {1 Stub conventions}

    When the date range does not divide evenly by [offset], one period is irregular (the {e stub}).
    The stub convention determines where it goes and whether it is kept short or merged into its
    neighbor.

    The convention also determines the generation direction: {!Short_first} and {!Long_first}
    generate backward from [end_date]; {!Short_last} and {!Long_last} generate forward from
    [start_date]. *)

(** The type for stub conventions. *)
type stub =
  | Short_first  (** Short irregular period at the start. {b Default.} *)
  | Short_last  (** Short irregular period at the end. *)
  | Long_first
      (** Merge the stub into the second period, producing one long period at the start. *)
  | Long_last
      (** Merge the stub into the penultimate period, producing one long period at the end. *)

(** {1 Schedules} *)

type t
(** The type for schedules. A schedule with [n] periods has [n + 1] boundary dates. *)

val make :
  start_date:Date.t ->
  end_date:Date.t ->
  offset:Period.offset ->
  ?roll:roll ->
  ?stub:stub ->
  ?bdc:Calendar.bdc ->
  ?calendar:Calendar.t ->
  unit ->
  t
(** [make ~start_date ~end_date ~offset ()] generates a schedule of contiguous periods between
    [start_date] and [end_date].

    - [roll] defaults to {!Same_day}.
    - [stub] defaults to {!Short_first}.
    - [bdc] defaults to {!Calendar.Unadjusted}.
    - [calendar] defaults to {!Calendar.weekdays}.

    {b Date generation.} Interior dates are generated by applying multiples of [offset] to the
    anchor (not sequential shifting), which avoids day-of-month drift: [Jan 31 + 2 months = Mar 31],
    not [Mar 28]. The anchor is [end_date] for backward generation ({!Short_first}, {!Long_first})
    and [start_date] for forward generation ({!Short_last}, {!Long_last}).

    {b Business day adjustment.} The {!Calendar.bdc} is applied only to interior boundary dates. The
    [start_date] and [end_date] endpoints are contract boundaries and are never adjusted.

    @raise Invalid_argument if [end_date <= start_date] or if the offset produces no periods. *)

(** {1 Accessors} *)

val length : t -> int
(** [length s] is the number of periods in [s]. Always [>= 1]. *)

val dates : t -> Date.t array
(** [dates s] is a fresh copy of the adjusted boundary dates.
    [Array.length (dates s) = length s + 1]. *)

val unadjusted_dates : t -> Date.t array
(** [unadjusted_dates s] is a fresh copy of the unadjusted boundary dates.
    [Array.length (unadjusted_dates s) = length s + 1]. *)

val periods : t -> Period.t array
(** [periods s] is the adjusted periods derived from consecutive adjusted boundary dates. *)

val unadjusted_periods : t -> Period.t array
(** [unadjusted_periods s] is the unadjusted periods derived from consecutive unadjusted boundary
    dates. Use these for accrual calculations where the day count must reflect the contractual
    schedule rather than the adjusted payment dates. *)

(** {1 Conversion} *)

val to_timeline : t -> Timeline.t
(** [to_timeline s] is a {!Timeline.t} built from the adjusted periods of [s]. Equivalent to
    [Timeline.of_periods (periods s)]. *)

val to_unadjusted_timeline : t -> Timeline.t
(** [to_unadjusted_timeline s] is a {!Timeline.t} built from the unadjusted periods of [s]. *)

val to_events : (int -> Period.t -> float) -> t -> (Date.t * float) list
(** [to_events f s] pairs each adjusted period's start date with [f i period], producing an event
    list suitable for {!Series.of_events}. [i] is the zero-based period index and [period] is the
    adjusted period.

    {[
      let payments = Series.of_events (Schedule.to_events (fun _i _p -> -50_000.0) loan_sched)
    ]} *)

(** {1 Formatting} *)

val to_string : t -> string
(** [to_string s] is [s] formatted as ["YYYY-MM-DD..YYYY-MM-DD (N periods)"]. *)

val pp : Format.formatter -> t -> unit
(** [pp] formats a schedule with {!to_string}. *)
